Repository PUE-AI-ChatBot/PUE-FE, pull requests merged in 2022-09, with the labels that each got.

#4 [Feature] 채팅 프로토타입
  .eslintrc.json
  .gitignore
  README.md
  front-end/.eslintrc.json
  front-end/application/navigation/GNB.tsx
  front-end/application/navigation/NavigationProvider.tsx
  front-end/application/navigation/QuickButton.tsx
  front-end/application/navigation/index.tsx
  front-end/package.json
  front-end/pages/_app.tsx
  front-end/pages/chat/index.tsx
  front-end/pages/index.tsx
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/vercel.svg
  src/application/chat/ChatService.ts
  src/application/navigation/GNB.tsx
  src/application/navigation/NavigationProvider.tsx
  src/application/navigation/QuickButton.tsx
  src/application/navigation/index.tsx
  src/components/chat/Message.tsx
  src/components/chat/index.tsx
  src/components/input/ChatInput.tsx
  src/components/layout.tsx
  src/pages/_app.tsx
  src/pages/calender/index.tsx
  src/pages/chat/index.tsx
  src/pages/index.tsx
  styles/globals.css
  tailwind.config.js
  tsconfig.json
Labels: feature

#8 Feature/채팅 비즈니스 로직 개발
  .eslintrc.json
  next.config.js
  package-lock.json
  package.json
  src/application/chat/Adaptor.ts
  src/application/chat/ChatService.ts
  src/components/chat/Message.tsx
  src/components/chat/index.tsx
  src/components/navigation/GNB.tsx
  src/components/navigation/NavigationProvider.tsx
  src/components/navigation/QuickButton.tsx
  src/components/navigation/index.tsx
  src/domain/chat/Chat.ts
  src/domain/chat/ChatRepository.ts
  src/domain/chat/ChatTypes.ts
  src/infra/chat/ChatApi.ts
  src/infra/chat/ChatResource.ts
  src/infra/client/HttpClient.ts
  src/infra/client/SocketClient.ts
  src/pages/_app.tsx
  src/pages/chat/index.tsx
  src/utils/mock.ts
  tsconfig.json
Labels: feature, HIGH

#7 #feature/캘린더-UI epic clone -> commit
  .DS_Store
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/application/diary/DayResults.ts
  src/components/character/index.tsx
  src/components/character/message.tsx
  src/components/charts/Charts.tsx
  src/components/diary/Emotion.tsx
  src/components/diary/index.tsx
  src/components/navigation/QuickButton.tsx
  src/pages/_app.tsx
  src/pages/calendar/index.tsx
  src/pages/calender/index.tsx
  styles/calendar.css
  styles/globals.css
Labels: feature

#11 Feature/프로필 페이지 개발
  .gitignore
  package-lock.json
  package.json
  public/profile.jpg
  src/application/chat/ChatService.ts
  src/components/avatar/ProfileAvatar.tsx
  src/components/chat/index.tsx
  src/components/navigation/GNB.tsx
  src/components/navigation/QuickButton.tsx
  src/components/navigation/index.tsx
  src/components/profile/footer/index.tsx
  src/components/profile/history/Count.tsx
  src/components/profile/history/index.tsx
  src/components/profile/info/index.tsx
  src/components/profile/info/meta.tsx
  src/components/profile/setting/SettingItem.tsx
  src/components/profile/setting/index.tsx
  src/helper/mock.ts
  src/helper/styles/calendar.css
  src/helper/styles/defaultStyle.ts
  src/helper/styles/globals.css
  src/pages/_app.tsx
  src/pages/chat/index.tsx
  src/pages/profile/index.tsx
  tsconfig.json
Labels: feature, NORMAL

#19 Feature/차트 BE
  .DS_Store
  next.config.js
  package.json
  src/application/diary/DayResults.ts
  src/components/charts/Charts.tsx
  src/components/charts/RadioButton.tsx
  src/components/charts/option/Options.ts
  src/components/charts/option/Series.ts
  src/components/diary/emotion/DayEmotion.ts
  src/components/diary/emotion/Emotion.tsx
  src/components/diary/index.tsx
  src/components/login/Login.tsx
  src/components/login/TitleText.tsx
  src/components/navigation/index.tsx
  src/components/profile/info/index.tsx
  src/components/profile/info/meta.tsx
  src/helper/mock.ts
  src/helper/styles/calendar.css
  src/infra/client/HttpClient.ts
  src/infra/oauth/environment.d.ts
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/chart/chartApi.ts
  src/pages/calendar/index.tsx
  src/pages/enter/index.tsx
  tsconfig.json
Labels: feature

#16 Feature/채팅 기능 테스트 코드 작성
  .eslintrc.json
  jest.config.js
  jest.setup.js
  next.config.js
  package.json
  src/application/__tests__/chat/Adaptor.test.ts
  src/application/__tests__/chat/ChatService.test.ts
  src/application/chat/Adaptor.ts
  src/application/chat/ChatService.ts
  src/components/__tests__/chat/index.test.tsx
  src/components/chat/Message.tsx
  src/components/chat/index.tsx
  src/components/input/ChatInput.tsx
  src/components/navigation/GNB.tsx
  src/components/navigation/index.tsx
  src/components/profile/footer/index.tsx
  src/components/profile/history/Count.tsx
  src/components/profile/info/index.tsx
  src/components/profile/info/meta.tsx
  src/components/profile/setting/index.tsx
  src/domain/chat/ChatTypes.ts
  src/infra/__tests__/chat/ChatApi.test.ts
  src/infra/__tests__/chat/ChatResource.test.ts
  src/infra/__tests__/client/Socket.test.ts
  src/infra/chat/ChatApi.ts
  src/infra/chat/ChatResource.ts
  src/infra/client/HttpClient.ts
  src/infra/client/SocketClient.ts
  src/pages/profile/index.tsx
Labels: NORMAL, test
